import os, sys

# import of db_config.py from the parent directory
script_dir = os.path.dirname(__file__)              
parent_dir = os.path.dirname(script_dir)            
sys.path.append(parent_dir)
from db_config import get_connection

SKILLS = [
#  skill_name ,                             skill_description ,                                skill_category
("Python",                                 "General‑purpose, high‑level programming language",           "Programming Language"),
("Java",                                   "Object‑oriented language used for enterprise & Android",     "Programming Language"),
("JavaScript",                             "Language of the web for client‑ & server‑side apps",         "Programming Language"),
("TypeScript",                             "Typed superset of JavaScript that compiles to JS",           "Programming Language"),
("C#",                                     "Microsoft .NET object‑oriented language",                    "Programming Language"),
("C++",                                    "Performance‑focused, compiled systems language",             "Programming Language"),
("Go",                                     "Google’s concurrent systems language (Golang)",              "Programming Language"),
("Rust",                                   "Memory‑safe systems language with zero‑cost abstractions",   "Programming Language"),
("SQL",                                    "Structured Query Language for relational databases",         "Data / Database"),
("NoSQL",                                  "Non‑relational data stores (e.g., key‑value, document)",     "Data / Database"),
("PostgreSQL",                             "Open‑source relational database with advanced SQL",          "Data / Database"),
("MySQL",                                  "Widely‑used open‑source relational database",                "Data / Database"),
("Oracle Database",                        "Enterprise relational database by Oracle",                   "Data / Database"),
("MongoDB",                                "Document‑oriented NoSQL database",                           "Data / Database"),
("Redis",                                  "In‑memory key‑value store and cache",                        "Data / Database"),
("Azure SQL",                              "Microsoft Azure managed SQL database service",               "Cloud / DevOps"),
("AWS RDS",                                "Amazon managed relational database service",                 "Cloud / DevOps"),
("HTML",                                   "Markup language for structuring web content",                "Web"),
("CSS",                                    "Style‑sheet language for web presentation",                  "Web"),
("React",                                  "Component‑based JavaScript UI library by Meta",              "Web Framework"),
("Angular",                                "Google’s TypeScript web application framework",              "Web Framework"),
("Vue.js",                                 "Progressive JavaScript framework for UIs",                   "Web Framework"),
("Node.js",                                "Server‑side JavaScript runtime on V8",                       "Web Framework"),
("Django",                                 "Python MVC web framework",                                   "Web Framework"),
("Flask",                                  "Lightweight Python micro‑web framework",                     "Web Framework"),
("Spring Boot",                            "Java framework for standalone micro‑services",               "Web Framework"),
("ASP.NET",                                "Microsoft web framework on .NET platform",                   "Web Framework"),
("REST API",                               "Stateless HTTP API design pattern",                          "Web / API"),
("GraphQL",                                "Query language & runtime for APIs",                          "Web / API"),
("Docker",                                 "Containerization platform for app packaging",                "Cloud / DevOps"),
("Kubernetes",                             "Container orchestration system",                             "Cloud / DevOps"),
("Terraform",                              "Infrastructure‑as‑Code tool",                                "Cloud / DevOps"),
("Ansible",                                "Agentless IT automation & configuration",                    "Cloud / DevOps"),
("CI/CD",                                  "Continuous Integration & Continuous Delivery practices",     "Cloud / DevOps"),
("Git",                                    "Distributed version‑control system",                         "Tools"),
("GitHub",                                 "Cloud Git hosting & collaboration platform",                 "Tools"),
("GitLab",                                 "DevOps lifecycle platform with Git hosting",                 "Tools"),
("Jenkins",                                "Automation server for CI/CD pipelines",                      "Cloud / DevOps"),
("Linux",                                  "Open‑source Unix‑like operating system",                     "OS / Systems"),
("Windows Server",                         "Microsoft enterprise server OS",                             "OS / Systems"),
("Bash",                                   "Unix shell & scripting language",                            "OS / Systems"),
("PowerShell",                             "Task‑automation shell & language by Microsoft",              "OS / Systems"),
("AWS",                                    "Amazon Web Services cloud platform",                         "Cloud / DevOps"),
("Azure",                                  "Microsoft Azure cloud platform",                             "Cloud / DevOps"),
("Google Cloud",                           "Google Cloud Platform services",                             "Cloud / DevOps"),
("Salesforce",                             "CRM & cloud business platform",                              "Business / SaaS"),
("Tableau",                                "Data visualization & BI platform",                           "Data / BI"),
("Power BI",                               "Microsoft business‑intelligence suite",                      "Data / BI"),
("Looker",                                 "Google data analytics & BI platform",                        "Data / BI"),
("Excel",                                  "Spreadsheet for analysis & reporting",                       "Data / BI"),
("NumPy",                                  "Python numerical computing library",                         "Data / Python"),
("Pandas",                                 "Python data‑frame & analysis library",                       "Data / Python"),
("Matplotlib",                             "Python plotting & visualization library",                    "Data / Python"),
("Scikit‑learn",                           "Python machine‑learning library",                            "Data / AI"),
("TensorFlow",                             "Google deep‑learning framework",                             "Data / AI"),
("PyTorch",                                "Meta deep‑learning framework",                               "Data / AI"),
("Keras",                                  "High‑level neural‑network API",                              "Data / AI"),
("Natural Language Processing",            "Computational techniques for text & speech",                "Data / AI"),
("Computer Vision",                        "Algorithms for image / video analysis",                      "Data / AI"),
("Reinforcement Learning",                 "ML paradigm with reward‑driven agents",                      "Data / AI"),
("Deep Learning",                          "Neural‑network–based representation learning",               "Data / AI"),
("Machine Learning",                       "Algorithms that learn from data patterns",                   "Data / AI"),
("Data Mining",                            "Extracting patterns from large data sets",                   "Data / AI"),
("Data Visualization",                     "Graphical representation of data insights",                  "Data / BI"),
("Statistical Analysis",                   "Applying statistics to interpret data",                      "Data / Stats"),
("Time‑Series Analysis",                   "Analyzing data points over time",                            "Data / Stats"),
("Hypothesis Testing",                     "Statistical significance testing of claims",                 "Data / Stats"),
("Linear Regression",                      "Predictive model for continuous outcomes",                   "Data / Stats"),
("Logistic Regression",                    "Binary classification algorithm",                            "Data / Stats"),
("Clustering",                             "Unsupervised grouping of data points",                       "Data / AI"),
("K‑means",                                "Popular centroid‑based clustering algorithm",                "Data / AI"),
("Principal Component Analysis",           "Dimensionality‑reduction technique",                         "Data / AI"),
("BigQuery",                               "Google serverless data warehouse",                           "Cloud / Data"),
("Redshift",                               "Amazon fully managed data warehouse",                        "Cloud / Data"),
("Snowflake",                              "Cloud‑native data warehousing platform",                     "Cloud / Data"),
("ETL",                                    "Extract‑Transform‑Load data pipelines",                      "Data / Pipeline"),
("Airflow",                                "Workflow orchestration for data pipelines",                  "Data / Pipeline"),
("Kafka",                                  "Distributed event streaming platform",                       "Data / Pipeline"),
("Spark",                                  "Cluster‑computing engine for big data",                      "Data / Pipeline"),
("Hadoop",                                 "Distributed storage & processing framework",                 "Data / Pipeline"),
("MapReduce",                              "Parallel processing model for big data",                     "Data / Pipeline"),
("Distributed Systems",                    "Systems whose components run on networked computers",        "OS / Systems"),
("Microservices",                          "Fine‑grained, independently deployable services",            "Web / API"),
("Service Mesh",                           "Infrastructure layer for service‑to‑service communication",  "Cloud / DevOps"),
("gRPC",                                   "High‑performance RPC framework",                             "Web / API"),
("WebSockets",                             "Full‑duplex web communication protocol",                     "Web / API"),
("OAuth",                                  "Open standard for delegated authorization",                  "Security"),
("JWT",                                    "JSON Web Token for stateless auth",                          "Security"),
("Encryption",                             "Transforming data to secure from unauthorized access",       "Security"),
("Network Security",                       "Protecting data during transmission",                        "Security"),
("Penetration Testing",                    "Ethical hacking to find vulnerabilities",                    "Security"),
("Vulnerability Assessment",               "Systematic review of security weaknesses",                   "Security"),
("Firewall",                               "Network traffic filtering device",                           "Security"),
("VPN",                                    "Encrypted virtual private network tunnel",                   "Security"),
("Incident Response",                      "Process for handling security breaches",                     "Security"),
("Threat Modeling",                        "Identifying potential security threats",                     "Security"),
("Risk Assessment",                        "Evaluating likelihood and impact of risks",                  "Security"),
("Compliance",                             "Adhering to industry or legal standards",                    "Security"),
("HIPAA",                                  "US health‑data protection regulation",                       "Security"),
("GDPR",                                   "EU data‑protection regulation",                              "Security"),
("SOC 2",                                  "Audit standard for service‑provider controls",              "Security"),
("Product Management",                     "Overseeing product lifecycle & strategy",                    "Product / PM"),
("Roadmapping",                            "High‑level timeline of product milestones",                  "Product / PM"),
("Backlog Grooming",                       "Prioritizing tasks in product backlog",                      "Product / PM"),
("User Stories",                           "End‑user narratives for product requirements",               "Product / PM"),
("Scrum",                                  "Agile framework with sprints & ceremonies",                  "Project / Process"),
("Kanban",                                 "Visual workflow method for continuous delivery",             "Project / Process"),
("Sprint Planning",                        "Meeting to plan upcoming sprint work",                       "Project / Process"),
("Stakeholder Management",                 "Engaging & communicating with stakeholders",                 "Soft Skill"),
("Requirements Gathering",                 "Eliciting user and system needs",                            "Product / PM"),
("Wireframing",                            "Creating low‑fidelity UI layouts",                           "UX / UI"),
("Figma",                                  "Collaborative interface‑design platform",                    "UX / UI"),
("Adobe XD",                               "Adobe vector‑based UI/UX design tool",                       "UX / UI"),
("User Research",                          "Studying users to inform design decisions",                  "UX / UI"),
("A/B Testing",                            "Controlled experiment to compare variants",                  "Product / PM"),
("Design Thinking",                        "Human‑centered approach to innovation",                      "UX / UI"),
("Customer Journey Mapping",               "Visualizing user interactions over time",                    "UX / UI"),
("SEO",                                    "Search‑engine optimization techniques",                      "Marketing"),
("Google Analytics",                       "Web traffic measurement & analysis service",                 "Marketing"),
("Content Strategy",                       "Planning & managing content creation",                       "Marketing"),
("Copywriting",                            "Writing persuasive marketing text",                          "Marketing"),
("CI/CD Pipelines",                        "Automated build‑test‑deploy workflows",                      "Cloud / DevOps"),
("Infrastructure as Code",                 "Provisioning infra with declarative files",                  "Cloud / DevOps"),
("Serverless",                             "Cloud execution model without server mgmt",                  "Cloud / DevOps"),
("Lambda",                                 "AWS serverless compute service",                             "Cloud / DevOps"),
("Event‑Driven Architecture",              "Decoupled design based on events",                           "Cloud / DevOps"),
("Domain‑Driven Design",                   "Modeling software around business domains",                  "Web / Arch"),
("Test‑Driven Development",                "Writing tests before code implementation",                   "Web / Arch"),
("Unit Testing",                           "Testing individual code units in isolation",                 "Testing"),
("Integration Testing",                    "Testing combined components as a group",                     "Testing"),
("Selenium",                               "Browser automation for UI tests",                            "Testing"),
("Cypress",                                "Modern end‑to‑end testing framework",                        "Testing"),
("Playwright",                             "Microsoft end‑to‑end testing library",                       "Testing"),
("Postman",                                "API development & testing platform",                         "Web / API"),
("Swagger",                                "API description & documentation tool",                       "Web / API"),
("OpenAPI",                                "Specification for RESTful APIs",                             "Web / API"),
("RESTful Design",                         "Architectural style for stateless APIs",                     "Web / API"),
("GraphQL Federation",                     "Distributed GraphQL across sub‑services",                    "Web / API"),
("CI",                                     "Continuous Integration practice",                            "Cloud / DevOps"),
("CD",                                     "Continuous Delivery / Deployment practice",                  "Cloud / DevOps"),
("JIRA",                                   "Issue tracking & agile project tool",                        "Project / Process"),
("Confluence",                             "Team knowledge‑base wiki by Atlassian",                      "Project / Process"),
("Slack",                                  "Team instant‑messaging platform",                            "Tools"),
("Trello",                                 "Kanban‑style visual task board",                             "Project / Process"),
("Notion",                                 "Collaborative note & knowledge workspace",                   "Tools"),
("Zoom",                                   "Video‑conferencing platform",                                "Tools"),
("Data Engineering",                       "Building & maintaining data pipelines",                      "Data / Pipeline"),
("Data Warehousing",                       "Storing integrated data for analysis",                       "Data / BI"),
("Data Governance",                        "Policies & processes for data quality & security",           "Data / BI"),
("Metadata Management",                    "Organizing data about data assets",                          "Data / BI"),
("Data Quality",                           "Ensuring accuracy & consistency of data",                   "Data / BI"),
("SRE",                                    "Site‑Reliability Engineering practice",                      "Cloud / DevOps"),
("Observability",                          "Monitoring metrics, logs & traces for insight",              "Cloud / DevOps"),
("Prometheus",                             "Time‑series DB & monitoring toolkit",                        "Cloud / DevOps"),
("Grafana",                                "Visualization & alerting for metrics",                       "Cloud / DevOps"),
("ElasticSearch",                          "Distributed search & analytics engine",                      "Data / Search"),
("Kibana",                                 "Visualization UI for Elasticsearch data",                    "Data / Search"),
("Log Aggregation",                        "Centralizing log data from multiple sources",                "Data / Search"),
("CI/CD Automation",                       "Automated orchestration of build‑deploy pipeline",           "Cloud / DevOps"),
("Terraform Cloud",                        "HashiCorp SaaS for IaC workflows",                           "Cloud / DevOps"),
("Pulumi",                                 "IaC tool using general‑purpose languages",                   "Cloud / DevOps"),
("Chef",                                   "Configuration‑management tool",                              "Cloud / DevOps"),
("Puppet",                                 "Automation for infrastructure configuration",                "Cloud / DevOps"),
("Vagrant",                                "VM environment manager for developers",                      "Cloud / DevOps"),
("Helm",                                   "Kubernetes package manager",                                 "Cloud / DevOps"),
("Istio",                                  "Service mesh for traffic management & security",             "Cloud / DevOps"),
("ServiceNow",                             "IT service‑management SaaS",                                 "Business / SaaS"),
("Zendesk",                                "Customer‑support ticketing platform",                        "Business / SaaS"),
("Salesforce Lightning",                   "Salesforce modern UI framework",                             "Business / SaaS"),
("SAP",                                    "Enterprise resource‑planning software",                      "Business / ERP"),
("ERP",                                    "Integrated management of core business processes",           "Business / ERP"),
("Supply Chain",                           "Flow of goods & services management",                        "Business / ERP"),
("Financial Modeling",                     "Building abstract financial representations",                "Business / Finance"),
("SQL Alchemy",                            "Python ORM for SQL databases",                               "Data / Python"),
("Pytorch Lightning",                      "Lightweight PyTorch training framework",                     "Data / AI"),
("Hugging Face",                           "NLP models & transformers library",                          "Data / AI"),
("LangChain",                              "Framework for LLM‑powered apps",                             "Data / AI"),
("LLM Fine‑tuning",                        "Adapting large language models to tasks",                    "Data / AI"),
("Prompt Engineering",                     "Designing prompts for LLM behaviour",                        "Data / AI"),
("Computer Graphics",                      "Generating & manipulating visual content",                   "Graphics"),
("OpenGL",                                 "Cross‑language 2D/3D graphics API",                          "Graphics"),
("Unity",                                  "Real‑time 3D development platform",                          "Graphics"),
("Unreal Engine",                          "AAA game & simulation engine",                               "Graphics"),
("AR/VR",                                  "Augmented & Virtual Reality technologies",                   "Graphics"),
("CUDA",                                   "NVIDIA parallel‑computing platform",                         "Graphics"),
("OpenCV",                                 "Computer‑vision library",                                    "Graphics"),
("CV2",                                    "OpenCV Python module",                                       "Graphics"),
("Simulations",                            "Modeling system behavior over time",                         "Graphics"),
("Parallel Computing",                     "Concurrent execution of computations",                       "OS / Systems"),
("Multithreading",                         "Multiple threads within a process",                          "OS / Systems"),
("Distributed Tracing",                    "Tracing requests across distributed systems",                "Cloud / DevOps"),
("Zipkin",                                 "Distributed tracing system",                                 "Cloud / DevOps"),
("Jaeger",                                 "Cloud‑native tracing platform",                              "Cloud / DevOps"),
("Data Lake",                              "Centralized repository for raw data at scale",               "Data / Pipeline"),
("Delta Lake",                             "ACID table format on data lakes",                            "Data / Pipeline"),
("Iceberg",                                "High‑performance table format for lakes",                    "Data / Pipeline"),
("Deltalake",                              "Python bindings for Delta Lake",                             "Data / Pipeline"),
("Presto",                                 "Distributed SQL query engine",                               "Data / Pipeline"),
("Trino",                                  "Fork of PrestoSQL distributed engine",                       "Data / Pipeline"),
("Big Data",                               "Large‑scale data sets and processing",                       "Data / Pipeline"),
("Kafka Streams",                          "Stream‑processing library on Kafka",                         "Data / Pipeline"),
("Flume",                                  "Log data collection service for Hadoop",                     "Data / Pipeline"),
("NiFi",                                   "Data‑flow orchestration platform",                           "Data / Pipeline"),
("Sqoop",                                  "Bulk data transfer between Hadoop & RDBMS",                  "Data / Pipeline"),
("Spark Streaming",                        "Real‑time data stream processing in Spark",                  "Data / Pipeline"),
("Databricks",                             "Unified analytics platform on Spark",                        "Cloud / Data"),
("Azure Synapse",                          "Integrated analytics service on Azure",                      "Cloud / Data"),
("Amazon EMR",                             "AWS big‑data processing service",                            "Cloud / Data"),
("Glue",                                   "AWS serverless data integration service",                    "Cloud / Data"),
("Quicksight",                             "AWS cloud BI visualization service",                         "Data / BI"),
("Looker Studio",                          "Google cloud data visualization tool",                       "Data / BI"),
("Superset",                               "Open‑source data exploration & BI",                          "Data / BI"),
("Metabase",                               "Open‑source self‑service analytics",                         "Data / BI"),
("Critical Thinking",                      "Objective analysis & evaluation of issues",                  "Soft Skill"),
("Problem Solving",                        "Process of finding solutions to difficult issues",           "Soft Skill"),
("Communication",                          "Exchange of information effectively",                        "Soft Skill"),
("Collaboration",                          "Working jointly with others",                                "Soft Skill"),
("Time Management",                        "Planning & exercising conscious control of time",            "Soft Skill"),
("Presentation",                           "Organizing & delivering information orally",                 "Soft Skill"),
("Team Leadership",                        "Guiding and motivating a team to achieve goals",             "Soft Skill"),
("Mentoring",                              "Advising or training others, especially juniors",            "Soft Skill"),
("Customer Focus",                         "Orienting products or services around the customer",         "Soft Skill"),
("Product Strategy",                       "Long‑term vision and plan for a product",                    "Product / PM"),
("Go‑to‑Market",                           "Plan for delivering a product to customers",                 "Product / PM"),
("Competitive Analysis",                   "Assessing competitors to inform strategy",                   "Product / PM"),
("Market Research",                        "Collecting data about target markets",                       "Product / PM"),
("KPI Definition",                         "Selecting key performance indicators",                       "Product / PM"),
("OKR",                                    "Objectives & Key Results goal‑setting framework",            "Product / PM"),
("User Persona",                           "Archetypal representation of a user segment",                "Product / PM"),
("Story Mapping",                          "Visualizing product backlog in end‑to‑end workflow",         "Product / PM"),
("Wireframes",                             "Basic page layout illustrations",                            "UX / UI"),
("Prototype",                              "Early model of a product to test concepts",                  "UX / UI"),
("Usability Testing",                      "Evaluating product by testing with users",                   "UX / UI"),
("Accessibility",                          "Designing so people with disabilities can use products",     "UX / UI"),
("Data Ethics",                            "Responsible collection & use of data",                       "Data / Statistics"),
("Privacy",                                "Protecting personal information",                            "Security"),
("DevSecOps",                              "Integrating security into DevOps",                           "Cloud / DevOps"),
("Zero Trust",                             "Security model: never trust, always verify",                 "Security"),
("Identity & Access Management",           "Governance of user identities and permissions",              "Security"),
("OAuth2",                                 "Auth framework for delegated access",                        "Security"),
("OpenID Connect",                         "Identity layer on top of OAuth2",                            "Security"),
("PKI",                                    "Public‑key infrastructure for certificates",                 "Security"),
("Encryption at Rest",                     "Data encryption while stored",                               "Security"),
("TLS",                                    "Transport Layer Security protocol",                          "Security"),
("HTTPS",                                  "HTTP over TLS/SSL for secure web",                           "Security"),
("Load Balancing",                         "Distributing workloads across resources",                    "Cloud / DevOps"),
("HAProxy",                                "High‑availability load‑balancer",                            "Cloud / DevOps"),
("Nginx",                                  "High‑performance web server & reverse proxy",                "Web / DevOps"),
("Apache",                                 "Open‑source HTTP server",                                    "Web / DevOps"),
("Reverse Proxy",                          "Server that forwards client requests",                       "Web / DevOps"),
("CORS",                                   "Cross‑origin resource sharing policy",                       "Web / DevOps"),
("Browser DevTools",                       "Built‑in browser debugging tools",                           "Web"),
("Webpack",                                "JavaScript module bundler",                                  "Web"),
("Vite",                                   "Fast modern web build tool",                                 "Web"),
("Parcel",                                 "Zero‑config web application bundler",                        "Web")
]

SQL = """
INSERT INTO Skills (skill_name, skill_description, skill_category)
VALUES (%s,%s,%s)
ON CONFLICT (skill_name) DO UPDATE
  SET skill_description = EXCLUDED.skill_description,
      skill_category    = EXCLUDED.skill_category;
"""

def load_skills():
    conn = get_connection()
    try:
        with conn, conn.cursor() as cur:
            cur.executemany(SQL, SKILLS)
        print(f"✅  Upserted {len(SKILLS)} curated skills.")
    finally:
        conn.close()
